### ISSUE TITLE
Error when importing @clockwork-xyz/sdk module

### ISSUE THREAD

**Issue by mwrites** [clockwork-xyz/explorer#133]
How to import for the clockwork typescript module in a fresh project? I have tried importing it in a fresh anchor project (from the typescript tests folder).

### Config

```bash
solana --version: solana-cli 1.14.12 (src:979792ba; feat:4145199441)
anchor --version: anchor-cli 0.26.0
node --version: v16.14.0
```

### How to reproduce?

Reference project: [https://github.com/mwrites/test-ts-sdk](https://github.com/mwrites/test-ts-sdk)

1. `anchor create test-ts-sdk && cd test-ts-sdk`
2. `yarn add @clockwork-xyz/sdk@0.0.2`
3. Try to import the clockwork module in `tests/test-ts-sdk.ts`

```ts
import * as anchor from "@project-serum/anchor";
import { Program } from "@project-serum/anchor";
import { TestTsSdk } from "../target/types/test_ts_sdk";
import { SEED_QUEUE } from "@clockwork-xyz/sdk";

describe("test-ts-sdk", () => {
  anchor.setProvider(anchor.AnchorProvider.env());
  const program = anchor.workspace.TestTsSdk as Program<TestTsSdk>;

  it("Is initialized!", async () => {
    console.log(SEED_QUEUE); // 👈 This breaks
    
    const tx = await program.methods.initialize().rpc();
    console.log("Your transaction signature", tx);
  });
});
```
4. `anchor test` throws the below error 👇

```bash
$ /Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'

/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/@clockwork-xyz/sdk/lib/index.js:1
export * from "./addresses";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/tests/test-ts-sdk.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at Object.exports.loadFilesAsync (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at singleRun (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/mwrites/kitchen/kitchen-solana/clockwork-examples/test-ts-sdk/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.
```

**Comment by KaneLabs** [comment]
Changed build target to commonjs in 0.0.5

https://www.npmjs.com/package/@clockwork-xyz/sdk
